[book]
authors = ["Junya Hirashima"]
language = "ja"
src = "src"
title = "Linux Desktop Setup"

[preprocessor.alerts]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/0npv527yh9/linux-desktop-setup"
